### ISSUE TITLE
PDFObject Not Show and Only show Root File

### ISSUE THREAD

**Issue by edwinariesto** [pipwerks/PDFObject#278] opened 2022-11-09 02:13 UTC
![Screenshot 2022-11-09 101318](https://user-images.githubusercontent.com/6454971/200720434-a31302ac-b149-4661-b768-0863dfbcfcd8.png)
![Screenshot 2022-11-09 101010](https://user-images.githubusercontent.com/6454971/200720437-92629591-2a6d-4ebe-8d8b-0b5452f2aab6.png)
![Screenshot 2022-11-09 100930](https://user-images.githubusercontent.com/6454971/200720442-5ba14818-4b38-4107-9813-a31ea6d4efd1.png)
Help me.. :(
how can i display the view of a pdf document in a modal dialogbox or on an HTML page? because at this time it only displays the root file in the folder or directly downloads it without having to see it first

**Comment by pipwerks** [comment] 2022-11-17 06:28
Hello. It looks like your PHP may not be returning the correct PDF URL.

Try it with static code (no PHP) and see if it works as expected. If yes, you'll know the issue is the PHP.

Also, I see you've included pdfobject.js twice, I suggest removing one of them.

Good luck

**Comment by pipwerks** [comment] 2022-11-17 06:30
Closing the ticket, as this does not appear to be a PDFObject bug/issue.

**Closed by pipwerks** 2022-11-17 06:30 UTC
