### ISSUE TITLE
PDFObject as a React component?

### ISSUE THREAD

**Issue by thj-dk** [pipwerks/PDFObject#120] opened 2017-01-23 19:01 UTC
Does anyone have any experience using PDFObject with React?

**Comment by pipwerks** [comment] 2017-01-29 06:22
No, sorry. Haven't tried it.

Closing thread since this is not a bug submission.

**Closed by pipwerks** 2017-01-29 06:22 UTC

**Comment by jch254** [comment] 2017-03-02 08:49
I've been using it with React and it works well:

```
import React, { Component, PropTypes } from 'react';
import PDFObject from 'pdfobject';

class PdfViewer extends Component {
  componentDidMount() {
    const { pdfBlob, containerId } = this.props;

    PDFObject.embed(pdfBlob, `#${containerId}`);
  }

  render() {
    const { width, height, containerId } = this.props;

    return <div style={{ width, height }} id={containerId} />;
  }
}

PdfViewer.propTypes = {
  pdfBlob: PropTypes.string.isRequired,
  width: PropTypes.string,
  height: PropTypes.string,
  containerId: PropTypes.string,
};

PdfViewer.defaultProps = {
  width: '100%',
  height: '100%',
  containerId: 'pdf-viewer',
};

export default PdfViewer;
```

**Comment by Infinity0106** [comment] 2018-01-07 23:19
the coment on top works but you file has to be inside your src folder in case of local file from there you have to start your file route in my case i have src/test.pdf in the structure but I call it by PDFObject.embed("/test.pdf", "#pdf-viewer");

**Comment by tofanelli** [comment] 2018-06-05 21:11
@jch254 hey man, can you elaborate how to use this component? I'm lost here =\

Already installed the pdfObject and the prop-types... but, where to invoke them and use it?

Cheers =)

**Comment by HelenZeng** [comment] 2019-01-15 07:57
But it not worked in ipad browser, both chrome and safari.  @jch254

**Comment by pipwerks** [comment] 2024-01-30 19:35
Thanks. Coincidentally I'm working on a PDFObject Vue component, I will look into making a React one as well. In the meantime you can use https://github.com/sugarshin/react-pdfobject/

**Comment by ricky11** [comment] 2024-11-18 01:03
Hi, @pipwerks is their a vue 2 solution?

**Comment by pipwerks** [comment] 2024-11-21 03:39
Hi @ricky11 No, but you could fork the [Vue 3 component](https://github.com/pipwerks/pdfobject-vue) and mod it to work with Vue 2
