### ISSUE TITLE
This browser does not support inline PDFs. Please download the PDF to view it: Download PDF

### ISSUE THREAD

**Issue by kouwoo** [pipwerks/PDFObject#153] opened 2017-11-15 02:26 UTC
In some IE browser，there will warn a message
"This browser does not support inline PDFs. Please download the PDF to view it: Download PDF",

**Comment by pipwerks** [comment] 2017-11-15 21:12
Duplicate of https://github.com/pipwerks/PDFObject/issues/125

**Closed by pipwerks** 2017-11-15 21:12 UTC
