### ISSUE TITLE
The variable isSafariOsx has not been declared

### ISSUE THREAD

**Issue by Rob1708** [pipwerks/PDFObject#212] opened 2020-04-30 11:58 UTC
As a result our builds fail.

**Comment by johnhunter** [comment] 2020-05-01 11:04
Sorry, my bad. I'll raise a PR

**Comment by NielsHolt** [comment] 2020-05-01 11:07
I have already made a PR, so we just wait for @Rob1708 to include it :-)

**Comment by NielsHolt** [comment] 2020-05-01 11:08
I have already made a PR, so we just wait for @pipwerks to include it :-)

**Comment by johnhunter** [comment] 2020-05-01 11:09
Nice https://github.com/pipwerks/PDFObject/pull/213

**Comment by Rob1708** [comment] 2020-05-06 09:32
Perhaps assigning the pull request to @pipwerks will help him notice there is an issue that he can quickly resolve…

**Comment by johnhunter** [comment] 2020-05-07 15:25
I think @pipwerks is the only one with permissions to assign reviewers :)

**Comment by fgandara** [comment] 2020-07-16 15:25
hey guys, 
Just used the generator on the page, correct path on the .js library that I just got from cloning the repo, and have the same issue.
on: 
Firefox 78.0.2 
Google Chrome | 84.0.4147.89 (Official Build) (64-bit)  -- windows and linux

**Comment by johnhunter** [comment] 2020-07-16 15:29
The fix PR https://github.com/pipwerks/PDFObject/pull/213 has not been merged. @pipwerks is the one with permissions to do so.

**Comment by johnhunter** [comment] 2020-07-20 09:57
Hi @pipwerks. I hate to be a pain, particularly since the root cause was my bad, but is there any chance we can get a new version published on npm? I've been using a fork of this repo but consuming that has some incompatibly issues with Dependabot that I need to address. Thanks.

**Comment by pipwerks** [comment] 2020-09-16 04:17
Sorry for the delay. Merged #213. Closing issue.

I am in the process of reviewing the code again and will try to test/push asap.

**Closed by pipwerks** 2020-09-16 04:17 UTC

**Comment by johnhunter** [comment] 2020-09-17 09:07
That's great, thanks @pipwerks. Do you think we'll get an npm version out soon?

**Comment by pipwerks** [comment] 2020-09-22 09:09
Done https://www.npmjs.com/package/pdfobject
Thanks for the help, lemme know if you run into anything

**Comment by johnhunter** [comment] 2020-09-22 09:11
Fantastic!, thanks for getting it all though 🙌

**Comment by pipwerks** [comment] 2020-09-22 09:15
There are a few new options, see https://pdfobject.com for details
