### ISSUE TITLE
PDF not rendering on Chrome, Just OPEN button there to download

### ISSUE THREAD

**Issue by ankitpdstf** [pipwerks/PDFObject#211] opened 2020-04-29 13:03 UTC
I have embeded its code in my .ejs file. But i am always getting this "Open" Button in Chrome instead of rendering it. I tried this on different laptops, and different browsers like Mozila, safari but getting the same result. Just Microsoft Edge is rendering the file and not giving me that "Open" Button. Dont know what is wrong there
![96a95d0c-855f-4a98-b4d8-f8324becb59f](https://user-images.githubusercontent.com/56149510/80599006-db9c8300-8a47-11ea-918f-8f411598396e.jpg)

**Comment by pipwerks** [comment] 2020-04-30 05:55
Unfortunately, without seeing your code, I can't provide any comments or suggestions. Closing since this is not a bug report, but feel free to provide more info if you're still stuck. Best advice I can give at this point is to follow the examples on PDFObject.com

**Closed by pipwerks** 2020-04-30 05:55 UTC

**Comment by bsmith-self** [comment] 2022-02-28 19:21
Hi- I can confirm this behavior. In fact, it happens on the official example:
![Screen Shot 2022-02-28 at 1 18 57 PM](https://user-images.githubusercontent.com/86080441/156044938-53b69c53-ffd3-479f-8d91-8d34bafe6b97.png)

Best I can tell, Chrome started disabling the embedded PDF viewer by default. The fallback is this Open button, which just downloads the PDF. You can turn the viewer back on in your browser settings, but it's buried pretty deep:

![Screen Shot 2022-02-28 at 1 14 27 PM](https://user-images.githubusercontent.com/86080441/156045080-c7e6e5ee-d8f5-4e1e-87ab-421a469ed1ce.png)
 
PDFObject of course would have no control over this setting or how Chrome decides to render embeds. However, I wonder if there's a way to detect the status of this setting? Would be nice to be able to have my code treat the "on desktop chrome but embeds disabled" case the same way it treats `supportsPDFs`. But I understand Chrome may not expose this information in any way.

**Comment by pipwerks** [comment] 2022-02-28 19:42
Thanks for the report. I guess the experience will vary... I don't have the same results as you (I'm on macOS, latest Chrome). 

<img width="1310" alt="Chome macOS PDFObject com" src="https://user-images.githubusercontent.com/300566/156047737-0d6d9b1d-919c-45cc-ad98-dbf373887e2a.png">

I'm not sure whether the embed can be detected; most browsers are disabling this type of detection in an effort to prevent fingerprinting. I will look into it.

**Comment by bsmith-self** [comment] 2022-02-28 19:51
It is also possible that disabling the embed isn't a Chrome default, and is a default enforced by my organization or something. Let me try on another computer.

**Comment by bsmith-self** [comment] 2022-02-28 19:57
Ok yes, I tried it on Chromium 101 on my personal laptop and Chrome on another laptop and both of them render the PDF by default. So I'm now thinking it might have been part of my company's IT policy or something to disable PDF embeds by default.
