### ISSUE TITLE
Not rendering the example pdf in Firefox 46.0.1

### ISSUE THREAD

**Issue by JJ92Git** [pipwerks/PDFObject#82] opened 2016-05-29 08:20 UTC
Cannot see the example pdf when using Firefox 46.0.1, although it works well when I use Safari 9.1.1

**Comment by pipwerks** [comment] 2016-05-29 08:51
Loading fine in 46.0.1 on my Mac.

Are you getting any warnings in your Dev tools console?

**Comment by JJ92Git** [comment] 2016-05-30 11:37
Hi Phillip,

Sorry I’m a bit of a newbie at this.  I do have a message in Console as follows:

Error: Permission denied to access property "toString"
POST https://fqtag.com/pixel?s=60042
200 OK
182ms	pixel?r...td=1743 (line 1)
 <>
Error: Permission denied to access property "toString"

Does this help?

I was running NoScript in Firefox but have disabled that with no real difference.  The container renders but there is no content displayed.  As I said though it works fine in Safari.

Regards,

Andy

Andy Edouard

andy@edouard.co.uk

**Comment by JJ92Git** [comment] 2016-05-30 11:39
Sorry, do you want me to close the issue and take it offline as it is probably just my problem since your copy works well!

**Comment by pipwerks** [comment] 2016-05-31 01:32
I am not able to reproduce the issue, so I suspect it's something on your end. If it works in Safari, your JavaScript code should be fine. As you mentioned, you had NoScript running in FF which would kill it, I wonder if you have other FF extensions impacting the script as well.

If the container renders, it means PDFObject has executed and correctly wrote the embed code to the page. If the embed code is on the page yet the PDF is not displayed, the problem is likely due to the PDF itself, whether a corrupted file or malformed URL. You mentioned it works in Safari, so my assumption is that the file path (URL) is OK, but try testing in both browsers again, with the cache cleared/disabled.

If you'd like help troubleshooting, provide a link to your page and I'll take a look when I get a chance.

Closing this issue for now, as I suspect this is not a bug.

**Closed by pipwerks** 2016-05-31 01:32 UTC
