### ISSUE TITLE
no pdf inlining for Chrome 89.0.4389.90 on Windows 10 

### ISSUE THREAD

**Issue by peevees** [pipwerks/PDFObject#241] opened 2021-03-18 09:09 UTC
seems like chrome on windows 10 desktop doesn't support inlining pdfs anymore

![image](https://user-images.githubusercontent.com/13975214/111600364-a15be180-87d1-11eb-87d8-77c0500a76c4.png)

**Comment by MrSwitch** [comment] 2021-03-19 10:41
Same on Chrome Version 90.0.4430.30 (Official Build) beta (x86_64) on Mac OSx when visiting https://pdfobject.com/examples/detection.html

The issue appears to be `navigator.mimeTypes["application/pdf"]` is undefined

![Screen Shot 2021-03-19 at 10 41 00](https://user-images.githubusercontent.com/947163/111768283-a9825280-889f-11eb-85de-5cd777325b62.png)

**Comment by MrSwitch** [comment] 2021-03-19 11:08
Created a new dedicated thread for the deprecation of `nav.mimeTypes` #242

**Comment by theodore-s-beers** [comment] 2021-03-19 22:52
There's already a (perhaps fragile) [workaround](https://github.com/pipwerks/PDFObject/blob/3bce0829719848a29919d605ce4cfdeb7f317ae3/pdfobject.js#L54).

I guess what we see here is that Chrome will start to fail the `supportsPDFs` check, and that's all that the detection page is looking at. In actual use, the library performs other tests, e.g. `isModernBrowser`, to determine whether PDF embedding is supported. I can confirm anecdotally that things are still working in Chrome 90.

This issue seems to be a matter of fixing the detection page to reflect the more nuanced logic used in the library.

**Comment by pipwerks** [comment] 2021-03-20 05:14
Thanks for the heads up. I guess it was just a matter of time. It's a shame they don't provide feature detection in lieu of MIME types.

**Comment by pipwerks** [comment] 2021-03-20 05:45
Added to next update, will be released shortly.

**Closed by pipwerks** 2021-03-20 05:45 UTC
